---
title: "Automated Speed Enforcement Program by City of Chicago"
author: "rtamhankar"
date: "April 28, 2019"
output: html_document
---


##Insight 1
###Speed Enforcement Program effective?

First Visualization "Impact of Automated Speed Enforcement Program Violations decreasing over the years?" shows how the number of violations are reducing over the years till today. The trend in the number of violations is decreasing from the years 2015 -2019. It can be concluded that the decrease in the violations is a result of Automatic Speed Enforcement program. Hence, the Automatic Speed Enforcement program should be continued in future as the reduction in the number of violations would further help to eradicate the corresponding vehicle crashes/accidents. The line graph clearly represents the message of declining violations by plotting years on X-axis and total number of violations within a year on Y-axis.

While showing the decrease in the total violations over the year, I thought, if I show the percentage decrease for each quarter within a year, it would effectively portray the efficiency of the program. Hence, I was curious to know the trend of violations throughout the different quarters over the years. I chose the line graph for this visualization as well, as I could clearly portray the core message by plotting years and quarters on X-axis and violations on Y-axis.  
When the second visualization for "Quarter wise trend in the violations" was plotted, I found a very interesting fact that the percentage of violations is decreasing for all quarters except for the quarter2(Q2). If we consider Q2 of the years 2015,2016,2017 and,2018 we can clearly see that there is an increase in the % violations as compared to the previous quarter. As far as 2014 and 2019 are concerned, there is no data available for Q2-2014 as the program was launched in Q3-2014 and Q3-2019 has just the data till current date of April2019.The quarter wise trend in the violations convey the message that appropriate measures should be taken for reducing the number of violations in Quarter 2. Can the violations be monitored for the current Q2-2019 quarter to find out the root causes of sudden surge in the speed violations in Q2?  

**Conclusion**

The Speed Camera violation program seems very effective as there is a decrease in number of violations over the years from 2015 to 2019.


##Insight 2
###Can the redundant cameras be removed?

First visualization "Top 10 Camera Ids with maximum violations" represents the camera wise number of violations in the descending order of violations captured by each camera. It represents the contribution of each camera in the total violations. I used bar chart which could clearly show the comparison between the violations captured by each camera.
From this graph, I found out the cameras where least number of violations are captured. There are two scenarios.
1.	Cameras need to be checked if they are working properly.
2.	Once it is confirmed that they are working properly, it can be assumed that there are minimal violations in those areas and people follow speed limit rules in those areas.
Those cameras can be considered as redundant and they can be deployed in the regions with more number of violations.
To convey this message, I plotted the cameras with less than total 1500 violations over the years. The second visualization conveys the actual number of violations captured by these cameras in the text table format. The visualization format is very easy to understand as there are less number of rows.

**Conclusion**

The cameras with less than 1500 total violations captured so far have been highlighted so that appropriate measures can be taken.

##Insight 3
###Exceptionally maximum violations within a single zip code?

In the first visualization, Zip code wise total violations have been shown with the help of a bar chart. It is observed that the number of violations are exceptionally maximum for one zip code. After plotting this graph, I realized that further analysis needs to be done to find out the community areas associated with this zip code. Hence, the second visualization is based on the number of violations pertaining to those wards within a single zip code. As there are only 4 community areas, they can be shown with the help of 'Packed bubbles chart' along with the additional details like community area code, community area names and number of violations.
By highlighting those community areas, we can suggest that the appropriate measures should be taken to reduce the number of violations in those areas. Increasing the fine for speeding ticket can be one of the solutions. If fine is increased in those areas, people may become more careful to drive within the speed limit. This would definitely reduce the number of crashes/accidents in those areas.

**Conclusion**

The community areas associated with the zip code with maximum number of violations have been highlighted so that steps can be taken to reduce the speed violations in the area.

##Roadmap for future enhancements
More analysis on the effectiveness of 'Automated Speed Enforcement program' can be done if the existing dataset is merged with a new dataset with additional relevant columns. Also, the analysis of number of violations can be extended further for the wards and all the community areas.

##References
1.[Dataset](https://data.cityofchicago.org/Transportation/Speed-Camera-Violations/gncf-3xbx)
2.[Community area names](https://www.chicagotribune.com/chi-community-areas-htmlstory.html)
3.[Tableau Public Link](https://public.tableau.com/profile/rujuta.tamhankar#!/vizhome/Automated_Speed_Enforcement_Program_By_City_Of_Chicago/Decreaseintheviolationsovertheyears)
